# Generated by Django 5.1.7 on 2025-04-04 19:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_stage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='current_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='active_projects', to='crm.stage'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='created_by',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='created_stages', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stage',
            name='order',
            field=models.PositiveIntegerField(),
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_companies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='crm.company'),
        ),
        migrations.AddField(
            model_name='stage',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='crm.company'),
        ),
        migrations.AlterUniqueTogether(
            name='stage',
            unique_together={('company', 'order')},
        ),
        migrations.RemoveField(
            model_name='stage',
            name='project',
        ),
    ]
