# Generated by Django 5.1.7 on 2025-04-06 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_project_current_stage_alter_stage_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='crm.company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stage',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='crm.company'),
            preserve_default=False,
        ),
    ]
