# Generated by Django 5.1.7 on 2025-03-28 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
        ('filesharing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='crm.project'),
        ),
    ]
