# Generated by Django 5.1.7 on 2025-06-03 17:38

import django.db.models.deletion
import filesharing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filesharing', '0003_collection_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='file',
            field=models.FileField(upload_to=filesharing.models.Photo.get_upload_path),
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='filesharing.collection')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subfolders', to='filesharing.folder')),
            ],
            options={
                'unique_together': {('collection', 'name', 'parent')},
            },
        ),
        migrations.AddField(
            model_name='photo',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to='filesharing.folder'),
        ),
    ]
