# Generated by Django 5.1.7 on 2025-06-14 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filesharing', '0004_alter_photo_file_folder_photo_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='is_client_selection',
            field=models.BooleanField(default=False, help_text='Позначає, чи є колекція клієнтською підбіркою'),
        ),
    ]
