# Generated by Django 5.1.7 on 2025-07-29 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filesharing', '0005_collection_is_client_selection'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='folder',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='folder',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folder_set', to='filesharing.collection'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='filesharing.folder'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photo_set', to='filesharing.folder'),
        ),
        migrations.AlterUniqueTogether(
            name='folder',
            unique_together={('name', 'collection', 'parent')},
        ),
    ]
